version: '3.7'
services:

  elrond:
    container_name: elrond
    restart: always
    volumes:
      - ./config/:/opt/app/config/
      - ./db/:/opt/app/db/
#      - ./logs/:/opt/app/logs/
#      - ./stats/:/opt/app/stats/
#    ports:
#      - '127.0.0.1:8080:8080'
#      - '127.0.0.1:38303:38303'
    build:
      context: .build
      args:
        ELROND_VERSION: ${ELROND_VERSION}
        CONFIG_VERSION: ${CONFIG_VERSION}
