version: '3.7'

services:

  autoupdater:
    container_name: autoupdater
#    image: docker:dind
    build:
      context: .build
      dockerfile: autoupdater.Dockerfile
#    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/Elrond/
    environment:
      USE_COMPOSE_FILE: ${USE_COMPOSE_FILE}
      RETRY_TIME_DONT_GET_TAG: ${RETRY_TIME_DONT_GET_TAG}
      RETRY_TIME_GET_TAG: ${RETRY_TIME_GET_TAG}
      GH_CREDENTIAL: ${GH_CREDENTIAL}