version: '3.7'

x-custom:
  # Templates anchors
  build_env: &build_env
    ELROND_VERSION: ${ELROND_VERSION}
    CONFIG_VERSION: ${CONFIG_VERSION}

  app_tmp: &app_tmp
#    restart: always
    build:
      context: .build
      args:
        <<: *build_env

services:

  elrond-1:
    <<: *app_tmp
    container_name: elrond-1
    volumes:
      - ./data/elrond-1/config/:/opt/app/config/
      - ./data/elrond-1/db/:/opt/app/db/

  elrond-2:
    <<: *app_tmp
    container_name: elrond-2
    volumes:
      - ./data/elrond-2/config/:/opt/app/config/
      - ./data/elrond-2/db/:/opt/app/db/
