name: Docker Image CI

on: [push]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@master
      # - uses: actions/checkout@v1
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: mrz1703/elrond-node/autoupdater
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # dockerfile: ./.build/autoupdater.Dockerfile
          registry: docker.pkg.github.com
          cache: true

      # - name: docker build
      #   uses: actions/docker/cli@master
      #   with:
      #     args: build -t mrz1703/elrond-node-autoupdater -f ./.build/autoupdater.Dockerfile .

      # - name: docker login
      #   uses: actions/docker/login@master
      #   env:
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # - name: docker push
      #   uses: actions/docker/cli@master
      #   with:
      #     args: push mrz1703/elrond-node-autoupdater